### PR TITLE
Update AWS Developer Associate Lambda Lab

### PR DESCRIPTION
**Pull request by mtloria**
I ran into an issue where the provided example code was not compatible with the default node version when creating my Lambda Function for this lab. These were the updates I made to get everything to work.

### CODE REVIEW

**Comment by skwashd** [comment]
I had the same issue with the lab in the serverless  section of the DVA-C02 course. At the start of the course they say the course is up to date as of June 2023.

**Comment by jbshu4546** [comment]
+1

**Comment by robsutcliffe** [comment]
+1

**Comment by jlyons210** [comment]
The code in the repo works with Node.js 16.x. I did a similar modification to get it to work under Node.js 18.x.
```javascript
import https from 'https';

const url = "https://www.amazon.com";

export const handler = async (event, context) => {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      resolve(res.statusCode);
    }).on('error', (e) => {
      reject(new Error(e));
    });
  });
};
```

**Comment by skwashd** [comment]
A Cloud Guru support closed my bug report and told me to pay closer attention to the instructions.

**Comment by mtloria** [comment]
> A Cloud Guru support closed my bug report and told me to pay closer attention to the instructions.

Interesting. Was there a step for a selecting a specific Node version that I missed? I am no longer on a paid membership and cannot look at the lab details anymore. I will go ahead and close this PR though.

**Pull request closed without merging**
